name: Manual Input Workflow

on:
  workflow_dispatch:
    inputs:
      environ:
        description: "Choose the deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      version:
        description: "Enter the application version to deploy"
        required: true
        default: "latest"
      # debug:
      #   description: "Enable debug mode?"
      #   required: false
      #   default: "false"  ctrl + /
      #   type: boolean
    env:
     name: kishorebabu
     surname: talluri


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environ }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Debug Mode: ${{ github.event.inputs.debug }}"
          echo "$name:$surname"

      - name: Deploy to Staging
        if: github.event.inputs.environ == 'staging'
        run: echo "Deploying version ${{ github.event.inputs.version }} to Staging"

      - name: Deploy to Production
        if: github.event.inputs.environ == 'production'
        run: echo "Deploying version ${{ github.event.inputs.version }} to Production"

      - name: Enable Debug Mode
        if: github.event.inputs.debug == 'true'
        run: echo "Debug mode is enabled"
