name: Update README on PR

on:
    push:
  # pull_request:
  #   types:
  #     - closed
  #     - synchronize
      branches:
        - master

# jobs:
#   update-readme:
#     runs-on: ubuntu-latest

#     steps:
#       # - name: Checkout the repository
#       #   uses: actions/checkout@v4
#       #   with:
#       #     ref: ${{ github.head_ref }}

#       # - name: Update README file
#       #   run: |
#       #     echo "### Last PR Updated: $(date)" >> README.md
#       #     echo "### Latest Version: $TAG" >> README.md
#       - name: Get Latest Tag
#         id: get_tag
#         run: echo "TAG=$(git describe --tags --abbrev=0)"
#       - name: Update README.md
#         run: |
#           echo "### Latest Version: $TAG"
#           echo "### Latest Version: $TAG" >> README.md

#       # - name: Commit and Push Changes
#       #   run: |
#       #     git config --global user.email "kishore.t533@gmail.com"
#       #     git config --global user.name "kishore"
#       #     git add README.md
#       #     git commit -m "Auto-update README with PR timestamp" || echo "No changes to commit"
#       #     git push -u origin ${{ github.head_ref }}
jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all tags are fetched
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: false

      - name: Get Latest Tag
        id: latest_tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Print Latest Tag
        run: echo "The latest tag is $LATEST_TAG" >> README.md
      - name: Commit and Push Changes
        run: |
          git config --global user.email "kishore.t533@gmail.com"
          git config --global user.name "kishore"
          git add README.md
          git commit -m "Auto-update README with PR timestamp" || echo "No changes to commit"
          git push -u origin ${{ github.head_ref }} 