name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      environment:
        description: "Select the deploymenet  tag "
        required: true
        default: "v.1.1"
        type: choice
        options:
          - 
        

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display Selected Environment
        run: echo "Deploying to ${{ github.event.inputs.environment }}"

      - name: Deploy to Staging
        if: github.event.inputs.environment == 'staging'
        run: echo "Deploying to Staging environment"

      - name: Deploy to Production
        if: github.event.inputs.environment == 'production'
        run: echo "Deploying to Production environment"
