name: Manual Input Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      version:
        description: "Enter the application version to deploy"
        required: true
        default: "latest"
      debug:
        description: "Enable debug mode?"
        required: false
        default: "false"
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Debug Mode: ${{ github.event.inputs.debug }}"

      - name: Deploy to Staging
        if: github.event.inputs.environment == 'staging'
        run: echo "Deploying version ${{ github.event.inputs.version }} to Staging"

      - name: Deploy to Production
        if: github.event.inputs.environment == 'production'
        run: echo "Deploying version ${{ github.event.inputs.version }} to Production"

      - name: Enable Debug Mode
        if: github.event.inputs.debug == 'true'
        run: echo "Debug mode is enabled"
